# Generated by Django 2.0.7 on 2020-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_course_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_start_time',
            field=models.TimeField(null=True),
        ),
    ]
